import type { ResourceConfig } from "./types";

const publishedField = {
  name: "published",
  label: "Published",
  type: "switch" as const,
  help: "Visible on the public website",
};

export const homepageResource: ResourceConfig = {
  collection: "homepage_sections",
  title: "Homepage Content",
  singular: "Section",
  description: "Headlines, supporting copy and calls to action shown on the public homepage.",
  searchKeys: ["section", "heading", "subheading"],
  publishable: true,
  defaultView: "cards",
  card: {
    title: "heading",
    eyebrow: "section",
    body: "subheading",
    meta: ["cta_label"],
  },
  fields: [
    {
      name: "section",
      label: "Section name",
      type: "text",
      required: true,
      placeholder: "Hero",
      group: "Basics",
    },
    { name: "order", label: "Display order", type: "number", placeholder: "1", group: "Basics" },
    { name: "heading", label: "Heading", type: "text", required: true, full: true, group: "Basics" },
    {
      name: "subheading",
      label: "Supporting text",
      type: "richtext",
      full: true,
      placeholder: "Write a warm sentence or two…",
      group: "Basics",
    },
    {
      name: "image_url",
      label: "Section image",
      type: "image",
      folder: "homepage",
      group: "Media",
    },
    {
      name: "cta_label",
      label: "Button label",
      type: "text",
      placeholder: "Plan your visit",
      group: "Call to action",
    },
    {
      name: "cta_link",
      label: "Button link",
      type: "text",
      placeholder: "/contact",
      group: "Call to action",
    },
    publishedField,
  ],
  columns: [
    { name: "image_url", label: "", kind: "image" },
    { name: "section", label: "Section" },
    { name: "heading", label: "Heading", kind: "truncate" },
    { name: "order", label: "Order", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const leadershipResource: ResourceConfig = {
  collection: "leaders",
  title: "Leadership",
  singular: "Leader",
  description: "Pastors, ministers and department heads featured on the leadership page.",
  searchKeys: ["name", "role", "bio"],
  publishable: true,
  defaultView: "cards",
  card: { title: "name", eyebrow: "role", body: "bio", image: "image_url" },
  fields: [
    { name: "name", label: "Full name", type: "text", required: true, group: "Profile" },
    { name: "role", label: "Role", type: "text", required: true, group: "Profile" },
    { name: "bio", label: "Biography", type: "richtext", full: true, group: "Profile" },
    {
      name: "image_url",
      label: "Portrait",
      type: "image",
      folder: "leaders",
      help: "Drag a portrait here — a square photo looks best",
      group: "Photo",
    },
    { name: "order", label: "Display order", type: "number", group: "Profile" },
    publishedField,
  ],
  columns: [
    { name: "image_url", label: "", kind: "image" },
    { name: "name", label: "Name" },
    { name: "role", label: "Role", hideOnMobile: true },
    { name: "order", label: "Order", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const ministriesResource: ResourceConfig = {
  collection: "ministries",
  title: "Ministries",
  singular: "Ministry",
  description: "Departments and fellowships people can join.",
  searchKeys: ["title", "description", "leader"],
  publishable: true,
  defaultView: "cards",
  card: {
    title: "title",
    eyebrow: "meets",
    body: "description",
    image: "image_url",
    meta: ["leader"],
  },
  fields: [
    { name: "title", label: "Ministry name", type: "text", required: true, group: "Details" },
    { name: "leader", label: "Ministry lead", type: "text", group: "Details" },
    { name: "description", label: "Description", type: "richtext", full: true, group: "Details" },
    {
      name: "meets",
      label: "Meeting schedule",
      type: "text",
      placeholder: "Sundays · 8:00 AM",
      group: "Details",
    },
    { name: "image_url", label: "Cover photo", type: "image", folder: "ministries", group: "Photo" },
    publishedField,
  ],
  columns: [
    { name: "image_url", label: "", kind: "image" },
    { name: "title", label: "Ministry" },
    { name: "meets", label: "Meets", hideOnMobile: true },
    { name: "leader", label: "Lead", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const sermonsResource: ResourceConfig = {
  collection: "sermons",
  title: "Sermons",
  singular: "Sermon",
  description: "Messages archived for streaming and download.",
  searchKeys: ["title", "speaker", "series"],
  publishable: true,
  defaultView: "cards",
  card: {
    title: "title",
    eyebrow: "speaker",
    body: "summary",
    image: "cover_url",
    badge: "series",
    meta: ["date", "duration"],
  },
  fields: [
    { name: "title", label: "Sermon title", type: "text", required: true, group: "Message" },
    { name: "speaker", label: "Speaker", type: "text", required: true, group: "Message" },
    { name: "series", label: "Series", type: "text", group: "Message" },
    {
      name: "date",
      label: "Date preached",
      type: "text",
      placeholder: "July 26, 2026",
      group: "Message",
    },
    { name: "duration", label: "Duration", type: "text", placeholder: "48 min", group: "Message" },
    { name: "summary", label: "Summary", type: "richtext", full: true, group: "Message" },
    { name: "cover_url", label: "Cover image", type: "image", folder: "sermons", group: "Media" },
    {
      name: "media_url",
      label: "Audio or video file",
      type: "media",
      folder: "sermons",
      accept: "audio/*,video/*",
      help: "Drop an MP3 or MP4 here — up to 20 MB",
      group: "Media",
    },
    {
      name: "video_url",
      label: "Or paste a YouTube link",
      type: "url",
      full: true,
      placeholder: "https://youtube.com/…",
      group: "Media",
    },
    publishedField,
  ],
  columns: [
    { name: "cover_url", label: "", kind: "image" },
    { name: "title", label: "Title", kind: "truncate" },
    { name: "speaker", label: "Speaker", hideOnMobile: true },
    { name: "series", label: "Series", kind: "badge", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const eventsResource: ResourceConfig = {
  collection: "events",
  title: "Events",
  singular: "Event",
  description: "Services, outreaches and special gatherings on the church calendar.",
  searchKeys: ["title", "location", "description"],
  publishable: true,
  defaultView: "cards",
  card: {
    title: "title",
    eyebrow: "date",
    body: "description",
    image: "image_url",
    badge: "status",
    meta: ["time", "location"],
  },
  fields: [
    { name: "title", label: "Event title", type: "text", required: true, group: "Details" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Upcoming", value: "upcoming" },
        { label: "Past", value: "past" },
      ],
      group: "Details",
    },
    { name: "date", label: "Date", type: "text", placeholder: "August 14, 2026", group: "Details" },
    {
      name: "time",
      label: "Time",
      type: "text",
      placeholder: "6:00 PM – 9:00 PM",
      group: "Details",
    },
    { name: "location", label: "Location", type: "text", full: true, group: "Details" },
    { name: "description", label: "Description", type: "richtext", full: true, group: "Details" },
    { name: "image_url", label: "Event flyer", type: "image", folder: "events", group: "Flyer" },
    publishedField,
  ],
  columns: [
    { name: "image_url", label: "", kind: "image" },
    { name: "title", label: "Event", kind: "truncate" },
    { name: "date", label: "Date", hideOnMobile: true },
    { name: "status", label: "Status", kind: "badge" },
    { name: "published", label: "Published", kind: "boolean", hideOnMobile: true },
  ],
};

export const galleryResource: ResourceConfig = {
  collection: "gallery",
  title: "Gallery",
  singular: "Photo",
  description: "Photographs grouped into albums for the public gallery.",
  searchKeys: ["title", "album", "caption"],
  publishable: true,
  defaultView: "cards",
  card: { title: "title", eyebrow: "album", body: "caption", image: "image_url" },
  fields: [
    { name: "title", label: "Photo title", type: "text", required: true, group: "Details" },
    { name: "album", label: "Album", type: "text", placeholder: "Worship", group: "Details" },
    {
      name: "image_url",
      label: "Photo",
      type: "image",
      folder: "gallery",
      help: "Drag your photo here — landscape photos look best",
      group: "Photo",
    },
    { name: "caption", label: "Caption", type: "textarea", full: true, group: "Details" },
    publishedField,
  ],
  columns: [
    { name: "image_url", label: "", kind: "image" },
    { name: "title", label: "Photo" },
    { name: "album", label: "Album", kind: "badge", hideOnMobile: true },
    { name: "caption", label: "Caption", kind: "truncate", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const announcementsResource: ResourceConfig = {
  collection: "announcements",
  title: "Announcements",
  singular: "Announcement",
  description: "Notices shown across the site and read out during services.",
  searchKeys: ["title", "body"],
  publishable: true,
  defaultView: "cards",
  card: { title: "title", body: "body", badge: "priority", image: "image_url" },
  fields: [
    { name: "title", label: "Title", type: "text", required: true, full: true, group: "Notice" },
    {
      name: "priority",
      label: "Priority",
      type: "select",
      options: [
        { label: "High", value: "high" },
        { label: "Normal", value: "normal" },
        { label: "Low", value: "low" },
      ],
      group: "Notice",
    },
    {
      name: "body",
      label: "Message",
      type: "richtext",
      full: true,
      required: true,
      placeholder: "Share the details the congregation needs…",
      group: "Notice",
    },
    { name: "image_url", label: "Attached image", type: "image", folder: "announcements", group: "Image" },
    publishedField,
  ],
  columns: [
    { name: "title", label: "Announcement", kind: "truncate" },
    { name: "body", label: "Message", kind: "html", hideOnMobile: true },
    { name: "priority", label: "Priority", kind: "badge", hideOnMobile: true },
    { name: "published", label: "Status", kind: "boolean" },
  ],
};

export const prayerResource: ResourceConfig = {
  collection: "prayer_requests",
  title: "Prayer Requests",
  singular: "Prayer request",
  description: "Requests submitted through the public prayer desk.",
  searchKeys: ["name", "email", "request", "category"],
  canCreate: false,
  defaultView: "cards",
  card: {
    title: "name",
    eyebrow: "category",
    body: "request",
    badge: "status",
    meta: ["email"],
  },
  fields: [
    { name: "name", label: "Name", type: "text", group: "Sender" },
    { name: "email", label: "Email", type: "email", group: "Sender" },
    { name: "category", label: "Category", type: "text", group: "Sender" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "New", value: "new" },
        { label: "Praying", value: "praying" },
        { label: "Answered", value: "answered" },
        { label: "Archived", value: "archived" },
      ],
      group: "Follow up",
    },
    { name: "request", label: "Request", type: "textarea", full: true, group: "Follow up" },
    { name: "confidential", label: "Confidential", type: "switch", group: "Follow up" },
  ],
  columns: [
    { name: "name", label: "From" },
    { name: "category", label: "Category", kind: "badge", hideOnMobile: true },
    { name: "request", label: "Request", kind: "truncate", hideOnMobile: true },
    { name: "status", label: "Status", kind: "badge" },
  ],
  emptyTitle: "No prayer requests yet",
  emptyBody: "Requests submitted from the public prayer page will appear here.",
};

export const messagesResource: ResourceConfig = {
  collection: "contact_messages",
  title: "Contact Messages",
  singular: "Message",
  description: "Enquiries sent through the public contact form.",
  searchKeys: ["name", "email", "subject", "message"],
  canCreate: false,
  defaultView: "cards",
  card: {
    title: "subject",
    eyebrow: "name",
    body: "message",
    badge: "status",
    meta: ["email"],
  },
  fields: [
    { name: "name", label: "Name", type: "text", group: "Sender" },
    { name: "email", label: "Email", type: "email", group: "Sender" },
    { name: "subject", label: "Subject", type: "text", full: true, group: "Sender" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Unread", value: "unread" },
        { label: "Read", value: "read" },
        { label: "Replied", value: "replied" },
      ],
      group: "Follow up",
    },
    { name: "message", label: "Message", type: "textarea", full: true, group: "Follow up" },
  ],
  columns: [
    { name: "name", label: "From" },
    { name: "subject", label: "Subject", kind: "truncate", hideOnMobile: true },
    { name: "created_at", label: "Received", kind: "date", hideOnMobile: true },
    { name: "status", label: "Status", kind: "badge" },
  ],
  emptyTitle: "No messages yet",
  emptyBody: "Messages sent from the public contact form will appear here.",
};

export const subscribersResource: ResourceConfig = {
  collection: "subscribers",
  title: "Newsletter Subscribers",
  singular: "Subscriber",
  description: "People receiving the church newsletter.",
  searchKeys: ["email", "name", "source"],
  fields: [
    { name: "email", label: "Email", type: "email", required: true },
    { name: "name", label: "Name", type: "text" },
    { name: "source", label: "Source", type: "text", placeholder: "footer" },
    {
      name: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Subscribed", value: "subscribed" },
        { label: "Unsubscribed", value: "unsubscribed" },
      ],
    },
  ],
  columns: [
    { name: "email", label: "Email" },
    { name: "name", label: "Name", hideOnMobile: true },
    { name: "source", label: "Source", kind: "badge", hideOnMobile: true },
    { name: "status", label: "Status", kind: "badge" },
  ],
  emptyTitle: "No subscribers yet",
  emptyBody: "Newsletter sign-ups from the site footer will appear here.",
};
